/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List provider accounts */
    get: operations['list-accounts']
    put?: never
    /**
     * Add a provider account
     * @description Credentials are verified against the provider before saving. The first account becomes the default.
     */
    post: operations['add-account']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get an account */
    get: operations['get-account']
    put?: never
    post?: never
    /** Delete an account */
    delete: operations['delete-account']
    options?: never
    head?: never
    /** Update an account */
    patch: operations['update-account']
    trace?: never
  }
  '/api/v1/accounts/{id}/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Verify an account against its provider */
    post: operations['test-account']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log in with username and password */
    post: operations['auth-login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log out the current session */
    post: operations['auth-logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current authentication identity */
    get: operations['auth-me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change the local user's password (revokes all sessions) */
    post: operations['auth-change-password']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/setup/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** First-run setup: create the local user (requires the API key) */
    post: operations['auth-setup-password']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Authentication status */
    get: operations['auth-status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/downloads/{id}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Retry a failed download */
    post: operations['retry-download']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream change events (Server-Sent Events)
     * @description Event names: torrent.added, torrent.updated, torrent.deleted, download.updated, account.changed, settings.changed, heartbeat (every 15s). Payloads are small notifications; re-fetch the resource. Slow consumers may miss events — re-sync on reconnect. Authenticate with the Bearer header or ?api_key= (EventSource cannot set headers).
     */
    get: operations['events']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get runtime settings */
    get: operations['get-settings']
    /** Replace runtime settings */
    put: operations['update-settings']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/system/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** System status */
    get: operations['get-status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/torrents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List torrents */
    get: operations['list-torrents']
    put?: never
    /** Add a torrent from a magnet link */
    post: operations['add-torrent']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/torrents/file': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add a torrent from a .torrent file (multipart) */
    post: operations['add-torrent-file']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/torrents/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a torrent */
    get: operations['get-torrent']
    put?: never
    post?: never
    /** Delete a torrent */
    delete: operations['delete-torrent']
    options?: never
    head?: never
    /** Update a torrent's category or settings */
    patch: operations['update-torrent']
    trace?: never
  }
  '/api/v1/torrents/{id}/files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Select which files to download */
    put: operations['select-files']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/torrents/{id}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Retry an errored or completed torrent from scratch */
    post: operations['retry-torrent']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Account: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Account.json
       */
      readonly $schema?: string
      /** Format: date-time */
      created_at: string
      enabled: boolean
      /** @description Account id */
      id: string
      /** @description Used when a torrent is added without an account */
      is_default: boolean
      /**
       * @description Provider kind
       * @enum {string}
       */
      kind: 'torbox' | 'realdebrid' | 'alldebrid' | 'premiumize' | 'debridlink'
      /** @description Display name (unique) */
      name: string
      /** Format: date-time */
      updated_at: string
      /** @description Live provider user info when available */
      user?: components['schemas']['User']
    }
    AddAccountInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AddAccountInBody.json
       */
      readonly $schema?: string
      credentials: components['schemas']['Credentials']
      /** @enum {string} */
      kind: 'torbox' | 'realdebrid' | 'alldebrid' | 'premiumize' | 'debridlink'
      /** @description Display name; defaults to the kind */
      name?: string
      set_default?: boolean
    }
    AddTorrentInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AddTorrentInBody.json
       */
      readonly $schema?: string
      /** @description Account id or name; default account when empty */
      account?: string
      category?: string
      /** @description Magnet URI */
      magnet: string
      /** @description Full per-torrent settings replacing the configured defaults (not merged) */
      settings?: components['schemas']['TorrentSettings']
    }
    AuthStatusOutBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AuthStatusOutBody.json
       */
      readonly $schema?: string
      /** @description Whether onboarding has completed */
      configured: boolean
      /** @description Configured auth mode: password or oidc; empty until onboarding */
      mode: string
    }
    ChangePasswordInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ChangePasswordInBody.json
       */
      readonly $schema?: string
      current_password: string
      new_password: string
    }
    Credentials: {
      /** @description API key / token for the provider */
      api_key?: string
    }
    Download: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Download.json
       */
      readonly $schema?: string
      /** Format: int64 */
      bytes_done: number
      /** Format: date-time */
      completed_at?: string
      error?: string
      file_id?: string
      filename: string
      /** Format: date-time */
      finished_at?: string
      id: string
      /** @description Path relative to the torrent directory */
      path: string
      /**
       * Format: double
       * @description 0..1
       */
      progress: number
      /** Format: date-time */
      queued_at: string
      /** Format: int64 */
      retry_count: number
      /** Format: int64 */
      size: number
      /** Format: date-time */
      started_at?: string
      /** @enum {string} */
      state:
        | 'pending'
        | 'unrestricting'
        | 'downloading'
        | 'downloaded'
        | 'unpacking'
        | 'done'
        | 'error'
      torrent_id: string
    }
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string
      /** @description Error message text */
      message?: string
      /** @description The value at the given location */
      value?: unknown
    }
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ErrorModel.json
       */
      readonly $schema?: string
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string
      /** @description Optional list of individual error details */
      errors?: components['schemas']['ErrorDetail'][]
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string
    }
    EvAccountChanged: {
      account_id?: string
      /** Format: date-time */
      at: string
      download_id?: string
      torrent_id?: string
      type: string
    }
    EvDownloadUpdated: {
      account_id?: string
      /** Format: date-time */
      at: string
      download_id?: string
      torrent_id?: string
      type: string
    }
    EvSettingsChanged: {
      account_id?: string
      /** Format: date-time */
      at: string
      download_id?: string
      torrent_id?: string
      type: string
    }
    EvTorrentAdded: {
      account_id?: string
      /** Format: date-time */
      at: string
      download_id?: string
      torrent_id?: string
      type: string
    }
    EvTorrentDeleted: {
      account_id?: string
      /** Format: date-time */
      at: string
      download_id?: string
      torrent_id?: string
      type: string
    }
    EvTorrentUpdated: {
      account_id?: string
      /** Format: date-time */
      at: string
      download_id?: string
      torrent_id?: string
      type: string
    }
    File: {
      id: string
      path: string
      selected: boolean
      /** Format: int64 */
      size: number
    }
    HealthOutBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/HealthOutBody.json
       */
      readonly $schema?: string
      ok: boolean
      version: string
    }
    Heartbeat: {
      /** Format: date-time */
      at: string
    }
    LoginInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/LoginInBody.json
       */
      readonly $schema?: string
      password: string
      username: string
    }
    MeOutBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/MeOutBody.json
       */
      readonly $schema?: string
      /** @description True when authenticated with the API key */
      api_key: boolean
      mode: string
      /** @description Set for session requests; empty for API-key requests */
      username?: string
    }
    SelectFilesInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SelectFilesInBody.json
       */
      readonly $schema?: string
      file_ids: string[]
    }
    SessionOutBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SessionOutBody.json
       */
      readonly $schema?: string
      username: string
    }
    Settings: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Settings.json
       */
      readonly $schema?: string
      categories?: string[]
      torrent_defaults: components['schemas']['TorrentSettings']
      /** Format: int64 */
      unpack_max_depth?: number
    }
    SetupPasswordInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SetupPasswordInBody.json
       */
      readonly $schema?: string
      password: string
      username: string
    }
    Status: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Status.json
       */
      readonly $schema?: string
      /** Format: int64 */
      accounts: number
      /** Format: int64 */
      disk_free_bytes: number
      /** Format: int64 */
      disk_total_bytes: number
      download_dir: string
      /** @description Count by download state */
      downloads: {
        [key: string]: number
      }
      /** @description Count by torrent status */
      torrents: {
        [key: string]: number
      }
      version: string
    }
    Torrent: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/Torrent.json
       */
      readonly $schema?: string
      account_id: string
      /** Format: date-time */
      added_at: string
      category?: string
      /** Format: date-time */
      completed_at?: string
      downloads: components['schemas']['Download'][]
      error?: string
      files: components['schemas']['File'][]
      hash: string
      id: string
      /**
       * Format: double
       * @description 0..1 progress of local downloads
       */
      local_progress: number
      name: string
      provider_id?: string
      /**
       * Format: double
       * @description 0..1 progress at the debrid provider
       */
      provider_progress: number
      /** @description Raw provider status string */
      provider_status?: string
      /** Format: int64 */
      retry_count: number
      /** Format: int64 */
      seeders: number
      settings: components['schemas']['TorrentSettings']
      /** Format: int64 */
      size: number
      /**
       * Format: int64
       * @description Provider-side bytes/sec
       */
      speed: number
      /** @enum {string} */
      status:
        | 'queued'
        | 'adding'
        | 'processing'
        | 'waiting_selection'
        | 'downloading'
        | 'uploading'
        | 'finished'
        | 'completed'
        | 'error'
      /** @description Human-readable detail about the current state */
      status_reason?: string
    }
    TorrentSettings: {
      /** @description Remove the torrent (files, provider) this long after a terminal error, e.g. 24h; empty = never */
      delete_on_error?: string
      /**
       * Format: int64
       * @description Automatic retries per file
       */
      download_retries?: number
      /** @description Skip paths matching this (case-insensitive) */
      exclude_regex?: string
      /**
       * @description What to do at the provider after local completion
       * @enum {string}
       */
      finished_action?: 'keep' | 'remove_from_provider'
      /** @description Delay before finished_action, e.g. 10m (Go duration) */
      finished_delay?: string
      /** @description Only download paths matching this (case-insensitive); overrides exclude */
      include_regex?: string
      /** @description Fail if not finished at the provider within this long, e.g. 72h; empty = never */
      lifetime?: string
      /** @description Download exactly these provider file ids */
      manual_files?: string[]
      /**
       * Format: int64
       * @description Skip files smaller than this many bytes
       */
      min_file_size?: number
      /**
       * Format: int64
       * @description Automatic re-adds after a provider error
       */
      torrent_retries?: number
      /** @description Extract archives after download */
      unpack?: boolean
    }
    UpdateAccountInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UpdateAccountInBody.json
       */
      readonly $schema?: string
      credentials?: components['schemas']['Credentials']
      enabled?: boolean
      name?: string
      set_default?: boolean
    }
    UpdateTorrentInBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UpdateTorrentInBody.json
       */
      readonly $schema?: string
      category?: string
      /** @description Full replacement of the torrent's settings (manual file selection is preserved; use the files endpoint for that) */
      settings?: components['schemas']['TorrentSettings']
    }
    User: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/User.json
       */
      readonly $schema?: string
      email?: string
      /** Format: date-time */
      expires_at?: string
      plan?: string
      premium: boolean
      username?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  'list-accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Account'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'add-account': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AddAccountInBody']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Account']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'get-account': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Account id or name */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Account']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'delete-account': {
    parameters: {
      query?: {
        /** @description Also delete the account's torrents (locally) */
        force?: boolean
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'update-account': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAccountInBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Account']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'test-account': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Account id or name */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'auth-login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginInBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOutBody']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'auth-logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'auth-me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOutBody']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'auth-change-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordInBody']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'auth-setup-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetupPasswordInBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOutBody']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'auth-status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthStatusOutBody']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'retry-download': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Download']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  events: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': (
            | {
                data: components['schemas']['EvAccountChanged']
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'account.changed'
                /** @description The event ID. */
                id?: number
                /** @description The retry time in milliseconds. */
                retry?: number
              }
            | {
                data: components['schemas']['EvDownloadUpdated']
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'download.updated'
                /** @description The event ID. */
                id?: number
                /** @description The retry time in milliseconds. */
                retry?: number
              }
            | {
                data: components['schemas']['Heartbeat']
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'heartbeat'
                /** @description The event ID. */
                id?: number
                /** @description The retry time in milliseconds. */
                retry?: number
              }
            | {
                data: components['schemas']['EvSettingsChanged']
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'settings.changed'
                /** @description The event ID. */
                id?: number
                /** @description The retry time in milliseconds. */
                retry?: number
              }
            | {
                data: components['schemas']['EvTorrentAdded']
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'torrent.added'
                /** @description The event ID. */
                id?: number
                /** @description The retry time in milliseconds. */
                retry?: number
              }
            | {
                data: components['schemas']['EvTorrentDeleted']
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'torrent.deleted'
                /** @description The event ID. */
                id?: number
                /** @description The retry time in milliseconds. */
                retry?: number
              }
            | {
                data: components['schemas']['EvTorrentUpdated']
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'torrent.updated'
                /** @description The event ID. */
                id?: number
                /** @description The retry time in milliseconds. */
                retry?: number
              }
          )[]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthOutBody']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'get-settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Settings']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'update-settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Settings']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Settings']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'get-status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Status']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'list-torrents': {
    parameters: {
      query?: {
        status?:
          | 'queued'
          | 'adding'
          | 'processing'
          | 'waiting_selection'
          | 'downloading'
          | 'uploading'
          | 'finished'
          | 'completed'
          | 'error'
        /** @description Account id or name */
        account?: string
        category?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Torrent'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'add-torrent': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AddTorrentInBody']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Torrent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'add-torrent-file': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          account?: string
          category?: string
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Torrent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'get-torrent': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Torrent id or info hash */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Torrent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'delete-torrent': {
    parameters: {
      query?: {
        /** @description Delete downloaded files */
        files?: boolean
        /** @description Delete at the debrid provider too */
        provider?: boolean
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'update-torrent': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTorrentInBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Torrent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'select-files': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SelectFilesInBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Torrent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
  'retry-torrent': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Torrent id or info hash */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Torrent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorModel']
        }
      }
    }
  }
}
