// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, expires_at, last_seen, user_agent FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.UserAgent,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, oidc_subject, oidc_email, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one
SELECT id, username, password_hash, oidc_subject, oidc_email, created_at, updated_at FROM users WHERE oidc_subject = ? AND oidc_subject != ''
`

func (q *Queries) GetUserByOIDCSubject(ctx context.Context, oidcSubject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOIDCSubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, oidc_subject, oidc_email, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, created_at, expires_at, last_seen, user_agent)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID        string
	UserID    string
	CreatedAt string
	ExpiresAt string
	LastSeen  string
	UserAgent string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeen,
		arg.UserAgent,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, username, password_hash, oidc_subject, oidc_email, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	OidcSubject  string
	OidcEmail    string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.OidcSubject,
		arg.OidcEmail,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen = ?, expires_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	LastSeen  string
	ExpiresAt string
	ID        string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeen, arg.ExpiresAt, arg.ID)
	return err
}

const updateUserOIDC = `-- name: UpdateUserOIDC :exec
UPDATE users SET oidc_subject = ?, oidc_email = ?, updated_at = ? WHERE id = ?
`

type UpdateUserOIDCParams struct {
	OidcSubject string
	OidcEmail   string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateUserOIDC(ctx context.Context, arg UpdateUserOIDCParams) error {
	_, err := q.db.ExecContext(ctx, updateUserOIDC,
		arg.OidcSubject,
		arg.OidcEmail,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
