// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countDownloadsByState = `-- name: CountDownloadsByState :one
SELECT COUNT(*) FROM downloads WHERE state = ?
`

func (q *Queries) CountDownloadsByState(ctx context.Context, state string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDownloadsByState, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDownloadsForTorrent = `-- name: DeleteDownloadsForTorrent :exec
DELETE FROM downloads WHERE torrent_id = ?
`

func (q *Queries) DeleteDownloadsForTorrent(ctx context.Context, torrentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadsForTorrent, torrentID)
	return err
}

const getDownload = `-- name: GetDownload :one
SELECT id, torrent_id, file_id, provider_link, direct_url, rel_path, filename, size, bytes_done, state, error, retry_count, queued_at, started_at, finished_at, unpack_started_at, unpack_finished_at, completed_at, updated_at FROM downloads WHERE id = ?
`

func (q *Queries) GetDownload(ctx context.Context, id string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.TorrentID,
		&i.FileID,
		&i.ProviderLink,
		&i.DirectUrl,
		&i.RelPath,
		&i.Filename,
		&i.Size,
		&i.BytesDone,
		&i.State,
		&i.Error,
		&i.RetryCount,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UnpackStartedAt,
		&i.UnpackFinishedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDownload = `-- name: InsertDownload :execrows
INSERT INTO downloads (
    id, torrent_id, file_id, provider_link, direct_url, rel_path, filename, size, bytes_done, state, error, retry_count,
    queued_at, started_at, finished_at, unpack_started_at, unpack_finished_at, completed_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(torrent_id, provider_link) DO NOTHING
`

type InsertDownloadParams struct {
	ID               string
	TorrentID        string
	FileID           string
	ProviderLink     string
	DirectUrl        string
	RelPath          string
	Filename         string
	Size             int64
	BytesDone        int64
	State            string
	Error            string
	RetryCount       int64
	QueuedAt         string
	StartedAt        sql.NullString
	FinishedAt       sql.NullString
	UnpackStartedAt  sql.NullString
	UnpackFinishedAt sql.NullString
	CompletedAt      sql.NullString
	UpdatedAt        string
}

func (q *Queries) InsertDownload(ctx context.Context, arg InsertDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDownload,
		arg.ID,
		arg.TorrentID,
		arg.FileID,
		arg.ProviderLink,
		arg.DirectUrl,
		arg.RelPath,
		arg.Filename,
		arg.Size,
		arg.BytesDone,
		arg.State,
		arg.Error,
		arg.RetryCount,
		arg.QueuedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.UnpackStartedAt,
		arg.UnpackFinishedAt,
		arg.CompletedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDownloadsByState = `-- name: ListDownloadsByState :many
SELECT id, torrent_id, file_id, provider_link, direct_url, rel_path, filename, size, bytes_done, state, error, retry_count, queued_at, started_at, finished_at, unpack_started_at, unpack_finished_at, completed_at, updated_at FROM downloads WHERE state = ? ORDER BY queued_at
`

func (q *Queries) ListDownloadsByState(ctx context.Context, state string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.TorrentID,
			&i.FileID,
			&i.ProviderLink,
			&i.DirectUrl,
			&i.RelPath,
			&i.Filename,
			&i.Size,
			&i.BytesDone,
			&i.State,
			&i.Error,
			&i.RetryCount,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UnpackStartedAt,
			&i.UnpackFinishedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadsForTorrent = `-- name: ListDownloadsForTorrent :many
SELECT id, torrent_id, file_id, provider_link, direct_url, rel_path, filename, size, bytes_done, state, error, retry_count, queued_at, started_at, finished_at, unpack_started_at, unpack_finished_at, completed_at, updated_at FROM downloads WHERE torrent_id = ? ORDER BY rel_path
`

func (q *Queries) ListDownloadsForTorrent(ctx context.Context, torrentID string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadsForTorrent, torrentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.TorrentID,
			&i.FileID,
			&i.ProviderLink,
			&i.DirectUrl,
			&i.RelPath,
			&i.Filename,
			&i.Size,
			&i.BytesDone,
			&i.State,
			&i.Error,
			&i.RetryCount,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UnpackStartedAt,
			&i.UnpackFinishedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownload = `-- name: UpdateDownload :exec
UPDATE downloads SET
    direct_url = ?, filename = ?, size = ?, bytes_done = ?, state = ?, error = ?, retry_count = ?,
    started_at = ?, finished_at = ?, unpack_started_at = ?, unpack_finished_at = ?, completed_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateDownloadParams struct {
	DirectUrl        string
	Filename         string
	Size             int64
	BytesDone        int64
	State            string
	Error            string
	RetryCount       int64
	StartedAt        sql.NullString
	FinishedAt       sql.NullString
	UnpackStartedAt  sql.NullString
	UnpackFinishedAt sql.NullString
	CompletedAt      sql.NullString
	UpdatedAt        string
	ID               string
}

func (q *Queries) UpdateDownload(ctx context.Context, arg UpdateDownloadParams) error {
	_, err := q.db.ExecContext(ctx, updateDownload,
		arg.DirectUrl,
		arg.Filename,
		arg.Size,
		arg.BytesDone,
		arg.State,
		arg.Error,
		arg.RetryCount,
		arg.StartedAt,
		arg.FinishedAt,
		arg.UnpackStartedAt,
		arg.UnpackFinishedAt,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateDownloadProgress = `-- name: UpdateDownloadProgress :exec
UPDATE downloads SET bytes_done = ?, updated_at = ? WHERE id = ?
`

type UpdateDownloadProgressParams struct {
	BytesDone int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadProgress, arg.BytesDone, arg.UpdatedAt, arg.ID)
	return err
}
