// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Download struct {
	ID               string
	TorrentID        string
	FileID           string
	ProviderLink     string
	DirectUrl        string
	RelPath          string
	Filename         string
	Size             int64
	BytesDone        int64
	State            string
	Error            string
	RetryCount       int64
	QueuedAt         string
	StartedAt        sql.NullString
	FinishedAt       sql.NullString
	UnpackStartedAt  sql.NullString
	UnpackFinishedAt sql.NullString
	CompletedAt      sql.NullString
	UpdatedAt        string
}

type ProviderAccount struct {
	ID          string
	Kind        string
	Name        string
	Credentials string
	Enabled     int64
	IsDefault   int64
	CreatedAt   string
	UpdatedAt   string
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Torrent struct {
	ID              string
	AccountID       string
	Hash            string
	Name            string
	DirName         string
	Category        string
	Status          string
	StatusReason    string
	Error           string
	Progress        float64
	Size            int64
	Speed           int64
	Seeders         int64
	ProviderID      string
	ProviderStatus  string
	Files           string
	Settings        string
	PayloadKind     string
	Payload         []byte
	RetryCount      int64
	AddedAt         string
	ProviderAddedAt sql.NullString
	ProviderEndedAt sql.NullString
	FilesSelectedAt sql.NullString
	CompletedAt     sql.NullString
	RetryAt         sql.NullString
	UpdatedAt       string
}
