// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_accounts.sql

package sqlcgen

import (
	"context"
)

const clearDefaultProviderAccount = `-- name: ClearDefaultProviderAccount :exec
UPDATE provider_accounts SET is_default = 0, updated_at = ? WHERE is_default = 1
`

func (q *Queries) ClearDefaultProviderAccount(ctx context.Context, updatedAt string) error {
	_, err := q.db.ExecContext(ctx, clearDefaultProviderAccount, updatedAt)
	return err
}

const countTorrentsForAccount = `-- name: CountTorrentsForAccount :one
SELECT COUNT(*) FROM torrents WHERE account_id = ?
`

func (q *Queries) CountTorrentsForAccount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTorrentsForAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProviderAccount = `-- name: DeleteProviderAccount :exec
DELETE FROM provider_accounts WHERE id = ?
`

func (q *Queries) DeleteProviderAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProviderAccount, id)
	return err
}

const getDefaultProviderAccount = `-- name: GetDefaultProviderAccount :one
SELECT id, kind, name, credentials, enabled, is_default, created_at, updated_at FROM provider_accounts WHERE is_default = 1
`

func (q *Queries) GetDefaultProviderAccount(ctx context.Context) (ProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getDefaultProviderAccount)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Credentials,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderAccount = `-- name: GetProviderAccount :one
SELECT id, kind, name, credentials, enabled, is_default, created_at, updated_at FROM provider_accounts WHERE id = ?
`

func (q *Queries) GetProviderAccount(ctx context.Context, id string) (ProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getProviderAccount, id)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Credentials,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderAccountByName = `-- name: GetProviderAccountByName :one
SELECT id, kind, name, credentials, enabled, is_default, created_at, updated_at FROM provider_accounts WHERE name = ?
`

func (q *Queries) GetProviderAccountByName(ctx context.Context, name string) (ProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getProviderAccountByName, name)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Credentials,
		&i.Enabled,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderAccount = `-- name: InsertProviderAccount :exec
INSERT INTO provider_accounts (id, kind, name, credentials, enabled, is_default, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProviderAccountParams struct {
	ID          string
	Kind        string
	Name        string
	Credentials string
	Enabled     int64
	IsDefault   int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) InsertProviderAccount(ctx context.Context, arg InsertProviderAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertProviderAccount,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Credentials,
		arg.Enabled,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listProviderAccounts = `-- name: ListProviderAccounts :many
SELECT id, kind, name, credentials, enabled, is_default, created_at, updated_at FROM provider_accounts ORDER BY created_at
`

func (q *Queries) ListProviderAccounts(ctx context.Context) ([]ProviderAccount, error) {
	rows, err := q.db.QueryContext(ctx, listProviderAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAccount{}
	for rows.Next() {
		var i ProviderAccount
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Credentials,
			&i.Enabled,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultProviderAccount = `-- name: SetDefaultProviderAccount :exec
UPDATE provider_accounts SET is_default = 1, updated_at = ? WHERE id = ?
`

type SetDefaultProviderAccountParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) SetDefaultProviderAccount(ctx context.Context, arg SetDefaultProviderAccountParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultProviderAccount, arg.UpdatedAt, arg.ID)
	return err
}

const updateProviderAccount = `-- name: UpdateProviderAccount :exec
UPDATE provider_accounts SET name = ?, credentials = ?, enabled = ?, updated_at = ? WHERE id = ?
`

type UpdateProviderAccountParams struct {
	Name        string
	Credentials string
	Enabled     int64
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateProviderAccount(ctx context.Context, arg UpdateProviderAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderAccount,
		arg.Name,
		arg.Credentials,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
