// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	ClearDefaultProviderAccount(ctx context.Context, updatedAt string) error
	CountDownloadsByState(ctx context.Context, state string) (int64, error)
	CountStartedDownloadsForTorrent(ctx context.Context, torrentID string) (int64, error)
	CountTorrents(ctx context.Context) (int64, error)
	CountTorrentsForAccount(ctx context.Context, accountID string) (int64, error)
	DeleteDownload(ctx context.Context, id string) error
	DeleteDownloadsForTorrent(ctx context.Context, torrentID string) error
	DeleteProviderAccount(ctx context.Context, id string) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteTorrent(ctx context.Context, id string) error
	GetDefaultProviderAccount(ctx context.Context) (ProviderAccount, error)
	GetDownload(ctx context.Context, id string) (Download, error)
	GetProviderAccount(ctx context.Context, id string) (ProviderAccount, error)
	GetProviderAccountByName(ctx context.Context, name string) (ProviderAccount, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetTorrent(ctx context.Context, id string) (Torrent, error)
	GetTorrentByHash(ctx context.Context, arg GetTorrentByHashParams) (Torrent, error)
	GetTorrentByProviderID(ctx context.Context, arg GetTorrentByProviderIDParams) (Torrent, error)
	InsertDownload(ctx context.Context, arg InsertDownloadParams) (int64, error)
	InsertProviderAccount(ctx context.Context, arg InsertProviderAccountParams) error
	InsertTorrent(ctx context.Context, arg InsertTorrentParams) error
	ListActiveTorrents(ctx context.Context) ([]Torrent, error)
	ListDownloads(ctx context.Context) ([]Download, error)
	ListDownloadsByState(ctx context.Context, state string) ([]Download, error)
	ListDownloadsForTorrent(ctx context.Context, torrentID string) ([]Download, error)
	ListProviderAccounts(ctx context.Context) ([]ProviderAccount, error)
	ListSettings(ctx context.Context) ([]ListSettingsRow, error)
	ListTorrents(ctx context.Context) ([]Torrent, error)
	ListTorrentsByAccount(ctx context.Context, accountID string) ([]Torrent, error)
	ListTorrentsByStatus(ctx context.Context, status string) ([]Torrent, error)
	SetDefaultProviderAccount(ctx context.Context, arg SetDefaultProviderAccountParams) error
	UpdateDownload(ctx context.Context, arg UpdateDownloadParams) error
	UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) error
	UpdateProviderAccount(ctx context.Context, arg UpdateProviderAccountParams) error
	UpdateTorrent(ctx context.Context, arg UpdateTorrentParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
