// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrents.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countTorrents = `-- name: CountTorrents :one
SELECT COUNT(*) FROM torrents
`

func (q *Queries) CountTorrents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTorrents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTorrent = `-- name: DeleteTorrent :exec
DELETE FROM torrents WHERE id = ?
`

func (q *Queries) DeleteTorrent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTorrent, id)
	return err
}

const getTorrent = `-- name: GetTorrent :one
SELECT id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders, provider_id, provider_status, files, settings, payload_kind, payload, retry_count, added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at FROM torrents WHERE id = ?
`

func (q *Queries) GetTorrent(ctx context.Context, id string) (Torrent, error) {
	row := q.db.QueryRowContext(ctx, getTorrent, id)
	var i Torrent
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Hash,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.StatusReason,
		&i.Error,
		&i.Progress,
		&i.Size,
		&i.Speed,
		&i.Seeders,
		&i.ProviderID,
		&i.ProviderStatus,
		&i.Files,
		&i.Settings,
		&i.PayloadKind,
		&i.Payload,
		&i.RetryCount,
		&i.AddedAt,
		&i.ProviderAddedAt,
		&i.ProviderEndedAt,
		&i.FilesSelectedAt,
		&i.CompletedAt,
		&i.RetryAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTorrentByHash = `-- name: GetTorrentByHash :one
SELECT id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders, provider_id, provider_status, files, settings, payload_kind, payload, retry_count, added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at FROM torrents WHERE account_id = ? AND hash = ? ORDER BY added_at DESC LIMIT 1
`

type GetTorrentByHashParams struct {
	AccountID string
	Hash      string
}

func (q *Queries) GetTorrentByHash(ctx context.Context, arg GetTorrentByHashParams) (Torrent, error) {
	row := q.db.QueryRowContext(ctx, getTorrentByHash, arg.AccountID, arg.Hash)
	var i Torrent
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Hash,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.StatusReason,
		&i.Error,
		&i.Progress,
		&i.Size,
		&i.Speed,
		&i.Seeders,
		&i.ProviderID,
		&i.ProviderStatus,
		&i.Files,
		&i.Settings,
		&i.PayloadKind,
		&i.Payload,
		&i.RetryCount,
		&i.AddedAt,
		&i.ProviderAddedAt,
		&i.ProviderEndedAt,
		&i.FilesSelectedAt,
		&i.CompletedAt,
		&i.RetryAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTorrentByProviderID = `-- name: GetTorrentByProviderID :one
SELECT id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders, provider_id, provider_status, files, settings, payload_kind, payload, retry_count, added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at FROM torrents WHERE account_id = ? AND provider_id = ? ORDER BY added_at DESC LIMIT 1
`

type GetTorrentByProviderIDParams struct {
	AccountID  string
	ProviderID string
}

func (q *Queries) GetTorrentByProviderID(ctx context.Context, arg GetTorrentByProviderIDParams) (Torrent, error) {
	row := q.db.QueryRowContext(ctx, getTorrentByProviderID, arg.AccountID, arg.ProviderID)
	var i Torrent
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Hash,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.StatusReason,
		&i.Error,
		&i.Progress,
		&i.Size,
		&i.Speed,
		&i.Seeders,
		&i.ProviderID,
		&i.ProviderStatus,
		&i.Files,
		&i.Settings,
		&i.PayloadKind,
		&i.Payload,
		&i.RetryCount,
		&i.AddedAt,
		&i.ProviderAddedAt,
		&i.ProviderEndedAt,
		&i.FilesSelectedAt,
		&i.CompletedAt,
		&i.RetryAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTorrent = `-- name: InsertTorrent :exec
INSERT INTO torrents (
    id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders,
    provider_id, provider_status, files, settings, payload_kind, payload, retry_count,
    added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTorrentParams struct {
	ID              string
	AccountID       string
	Hash            string
	Name            string
	Category        string
	Status          string
	StatusReason    string
	Error           string
	Progress        float64
	Size            int64
	Speed           int64
	Seeders         int64
	ProviderID      string
	ProviderStatus  string
	Files           string
	Settings        string
	PayloadKind     string
	Payload         []byte
	RetryCount      int64
	AddedAt         string
	ProviderAddedAt sql.NullString
	ProviderEndedAt sql.NullString
	FilesSelectedAt sql.NullString
	CompletedAt     sql.NullString
	RetryAt         sql.NullString
	UpdatedAt       string
}

func (q *Queries) InsertTorrent(ctx context.Context, arg InsertTorrentParams) error {
	_, err := q.db.ExecContext(ctx, insertTorrent,
		arg.ID,
		arg.AccountID,
		arg.Hash,
		arg.Name,
		arg.Category,
		arg.Status,
		arg.StatusReason,
		arg.Error,
		arg.Progress,
		arg.Size,
		arg.Speed,
		arg.Seeders,
		arg.ProviderID,
		arg.ProviderStatus,
		arg.Files,
		arg.Settings,
		arg.PayloadKind,
		arg.Payload,
		arg.RetryCount,
		arg.AddedAt,
		arg.ProviderAddedAt,
		arg.ProviderEndedAt,
		arg.FilesSelectedAt,
		arg.CompletedAt,
		arg.RetryAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveTorrents = `-- name: ListActiveTorrents :many
SELECT id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders, provider_id, provider_status, files, settings, payload_kind, payload, retry_count, added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at FROM torrents WHERE completed_at IS NULL ORDER BY added_at
`

func (q *Queries) ListActiveTorrents(ctx context.Context) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTorrents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Torrent{}
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Hash,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.StatusReason,
			&i.Error,
			&i.Progress,
			&i.Size,
			&i.Speed,
			&i.Seeders,
			&i.ProviderID,
			&i.ProviderStatus,
			&i.Files,
			&i.Settings,
			&i.PayloadKind,
			&i.Payload,
			&i.RetryCount,
			&i.AddedAt,
			&i.ProviderAddedAt,
			&i.ProviderEndedAt,
			&i.FilesSelectedAt,
			&i.CompletedAt,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTorrents = `-- name: ListTorrents :many
SELECT id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders, provider_id, provider_status, files, settings, payload_kind, payload, retry_count, added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at FROM torrents ORDER BY added_at DESC
`

func (q *Queries) ListTorrents(ctx context.Context) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, listTorrents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Torrent{}
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Hash,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.StatusReason,
			&i.Error,
			&i.Progress,
			&i.Size,
			&i.Speed,
			&i.Seeders,
			&i.ProviderID,
			&i.ProviderStatus,
			&i.Files,
			&i.Settings,
			&i.PayloadKind,
			&i.Payload,
			&i.RetryCount,
			&i.AddedAt,
			&i.ProviderAddedAt,
			&i.ProviderEndedAt,
			&i.FilesSelectedAt,
			&i.CompletedAt,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTorrentsByAccount = `-- name: ListTorrentsByAccount :many
SELECT id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders, provider_id, provider_status, files, settings, payload_kind, payload, retry_count, added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at FROM torrents WHERE account_id = ? ORDER BY added_at DESC
`

func (q *Queries) ListTorrentsByAccount(ctx context.Context, accountID string) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, listTorrentsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Torrent{}
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Hash,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.StatusReason,
			&i.Error,
			&i.Progress,
			&i.Size,
			&i.Speed,
			&i.Seeders,
			&i.ProviderID,
			&i.ProviderStatus,
			&i.Files,
			&i.Settings,
			&i.PayloadKind,
			&i.Payload,
			&i.RetryCount,
			&i.AddedAt,
			&i.ProviderAddedAt,
			&i.ProviderEndedAt,
			&i.FilesSelectedAt,
			&i.CompletedAt,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTorrentsByStatus = `-- name: ListTorrentsByStatus :many
SELECT id, account_id, hash, name, category, status, status_reason, error, progress, size, speed, seeders, provider_id, provider_status, files, settings, payload_kind, payload, retry_count, added_at, provider_added_at, provider_ended_at, files_selected_at, completed_at, retry_at, updated_at FROM torrents WHERE status = ? ORDER BY added_at
`

func (q *Queries) ListTorrentsByStatus(ctx context.Context, status string) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, listTorrentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Torrent{}
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Hash,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.StatusReason,
			&i.Error,
			&i.Progress,
			&i.Size,
			&i.Speed,
			&i.Seeders,
			&i.ProviderID,
			&i.ProviderStatus,
			&i.Files,
			&i.Settings,
			&i.PayloadKind,
			&i.Payload,
			&i.RetryCount,
			&i.AddedAt,
			&i.ProviderAddedAt,
			&i.ProviderEndedAt,
			&i.FilesSelectedAt,
			&i.CompletedAt,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTorrent = `-- name: UpdateTorrent :exec
UPDATE torrents SET
    name = ?, category = ?, status = ?, status_reason = ?, error = ?, progress = ?, size = ?, speed = ?, seeders = ?,
    provider_id = ?, provider_status = ?, files = ?, settings = ?, retry_count = ?,
    provider_added_at = ?, provider_ended_at = ?, files_selected_at = ?, completed_at = ?, retry_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateTorrentParams struct {
	Name            string
	Category        string
	Status          string
	StatusReason    string
	Error           string
	Progress        float64
	Size            int64
	Speed           int64
	Seeders         int64
	ProviderID      string
	ProviderStatus  string
	Files           string
	Settings        string
	RetryCount      int64
	ProviderAddedAt sql.NullString
	ProviderEndedAt sql.NullString
	FilesSelectedAt sql.NullString
	CompletedAt     sql.NullString
	RetryAt         sql.NullString
	UpdatedAt       string
	ID              string
}

func (q *Queries) UpdateTorrent(ctx context.Context, arg UpdateTorrentParams) error {
	_, err := q.db.ExecContext(ctx, updateTorrent,
		arg.Name,
		arg.Category,
		arg.Status,
		arg.StatusReason,
		arg.Error,
		arg.Progress,
		arg.Size,
		arg.Speed,
		arg.Seeders,
		arg.ProviderID,
		arg.ProviderStatus,
		arg.Files,
		arg.Settings,
		arg.RetryCount,
		arg.ProviderAddedAt,
		arg.ProviderEndedAt,
		arg.FilesSelectedAt,
		arg.CompletedAt,
		arg.RetryAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
